ci(actions): setup and testing
Co-authored-by: Ricardo Campos <ricardo.campos@encora.com>

diff --git a/.github/workflows/pr-close.yml b/.github/workflows/pr-close.yml
--- a/.github/workflows/pr-close.yml
+++ b/.github/workflows/pr-close.yml
@@ -5,13 +5,11 @@ on:
     types:
       - closed
     paths-ignore:
-      - ".**"
       - "**.md"
-      - "**.yml"
-      - "**.yaml"
 
 env:
-  NAME: gfp
+  REGISTRY: ghcr.io
+  NAME: nrfesampleapp
 
 jobs:
   # Clean up OpenShift when PR closed, no conditions
@@ -21,7 +19,7 @@ jobs:
     environment:
       name: dev
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Remove OpenShift artifacts
         run: |
           oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
@@ -30,29 +28,60 @@ jobs:
           # Remove old build runs, build pods and deployment pods
           oc delete all,pvc,secret -l app=${{ env.NAME }}-${{ github.event.number }}
 
-  # Promote images when PR merged and branch = main
-  promote-images:
-    name: Promote DEV images to TEST
+  # If merged, then handle any image promotion
+  image-promotion:
+    name: Image Promotion
+    outputs:
+      build: ${{ steps.check.outputs.build }}
+    env:
+      COMPONENT: nrfesampleapp-image
+      PREV: ${{ github.event.number }}
+      ZONE: test
+    environment:
+      name: test
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
     steps:
-      - name: Promote Backend Image to TEST
+      - name: Check for image changes
+        id: check
+        run: |
+          # Vars
+          IMG_PREV="${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PREV }}-${{ env.COMPONENT }}"
+          IMG_ZONE="${{ env.REGISTRY }}/${{ github.repository }}:${{ env.ZONE }}-${{ env.COMPONENT }}"
+          # Make sure an image exists to promote; grab SHA
+          if [[ ! $(docker pull "${IMG_PREV}") ]]; then
+              echo -e "\n No images to promote"
+              exit 0
+          fi
+          SHA_PREV=$(docker inspect -f '{{.Id}}' "${IMG_PREV}")
+          # Use blank SHA for promoted image, unless a real one exists instead
+          SHA_ZONE=""
+          if [[ $(docker pull "${IMG_ZONE}") ]]; then
+            SHA_ZONE=$(docker inspect -f '{{.Id}}' "${IMG_ZONE}")
+          fi
+          # Output SHAs
+          echo -e "\n${IMG_PREV}: ${SHA_PREV}"
+          echo -e "${IMG_ZONE}: ${SHA_ZONE}\n"
+          # If different, then trigger updates
+          if [[ "${SHA_PREV}" != "${SHA_ZONE}" ]]; then
+            echo "::set-output name=build::true"
+            echo "Image has changed"
+            # Login to OpenShift and select project
+            oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
+            oc project ${{ secrets.OC_NAMESPACE }}
+            oc delete is/${{ env.NAME }}-${{ env.ZONE}}-${{ env.COMPONENT }} || true
+            exit 0
+          fi
+          echo "Image promotion not required"
+      - name: Promote Service API Image
+        if: steps.check.outputs.build == 'true'
         uses: shrink/actions-docker-registry-tag@v2
         with:
-          registry: ghcr.io
+          registry: ${{ env.REGISTRY }}
           repository: ${{ github.repository }}
-          target: ${{ github.event.number }}-backend
+          target: ${{ env.PREV }}-${{ env.COMPONENT }}
           tags: |
-            test-backend
-
-      - name: Promote Frontend Image to TEST
-        uses: shrink/actions-docker-registry-tag@v2
-        with:
-          registry: ghcr.io
-          repository: ${{ github.repository }}
-          target: ${{ github.event.number }}-frontend
-          tags: |
-            test-frontend
+            ${{ env.ZONE }}-${{ env.COMPONENT }}
 
   # Notify when PR merged and branch = main
   merge-notification:
@@ -68,5 +97,4 @@ jobs:
           allow-repeats: false
           message: |
             Your Pull Request code is being promoted!  Please follow the link below.
-
             [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)
